[package]
name = "peaploy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
cc="*"

[dependencies]
tree-sitter = "0.22"
tree-sitter-python = "0.21" # Replace with the language you need
